name: Check Links on Push

on:
    push:
        branches:
            - main

jobs:
    check-links:
        runs-on: ubuntu-latest
        steps:
            - name: Check Links
              uses: paulschuberth/check-links-action@v1
              with:
                  start-url: 'https://maxcomperatore.com'
                  broken-link-message: 'broken link!'

    crawl_for_broken_links:
        runs-on: ubuntu-latest
        steps:
            - name: Check for broken links
              uses: ScholliYT/Broken-Links-Crawler-Action@v3.3.1
              with:
                  website_url: 'https://maxcomperatore.com'
                  verbose: 'true'
                  max_retry_time: 30
                  max_retries: 5